In [26]:
import numpy as np
a =np.array([[1,2,3],[4,5,6],[7,8,9]])  # Array
          #     0       1       2
          #   0  1 2  0  1 2   0 1 2
print(a[0:1,1:2]) #2
print(a[ :1,1: ])  #2,3
print(a[1:2,1: ])  #5,6
print(a[2: ])     #7,8,9

#print 4,5,6 from 1st index

[[2]]
[[2 3]]
[[5 6]]
[[7 8 9]]


In [27]:
print(a[ :2,1: ])

[[2 3]
 [5 6]]


In [28]:
#print(a[ :2,0:2])
print(a[1:2,1: ])

[[5 6]]


In [29]:
print(a[ :3,1: ])

[[2 3]
 [5 6]
 [8 9]]


In [30]:
import numpy as np

x=np.random.randint(0,20,(6,5))
print(x)

[[ 5 11  3 19  9]
 [16  4 12  1  9]
 [11  7  4  1  4]
 [ 7  0  2 19  8]
 [19  7  2 13 13]
 [17  6  0 11  9]]


In [31]:
x.shape=(2,15)   #30=1*30, 2*15,3*10,5*6,10*3,15*2,30*1
print(x)

[[ 5 11  3 19  9 16  4 12  1  9 11  7  4  1  4]
 [ 7  0  2 19  8 19  7  2 13 13 17  6  0 11  9]]


In [32]:
x.ravel()   #ravel flattens the array

array([ 5, 11,  3, 19,  9, 16,  4, 12,  1,  9, 11,  7,  4,  1,  4,  7,  0,
        2, 19,  8, 19,  7,  2, 13, 13, 17,  6,  0, 11,  9])

In [33]:
x.reshape(3,10)

array([[ 5, 11,  3, 19,  9, 16,  4, 12,  1,  9],
       [11,  7,  4,  1,  4,  7,  0,  2, 19,  8],
       [19,  7,  2, 13, 13, 17,  6,  0, 11,  9]])

In [34]:
print(x)

[[ 5 11  3 19  9 16  4 12  1  9 11  7  4  1  4]
 [ 7  0  2 19  8 19  7  2 13 13 17  6  0 11  9]]


In [35]:
x.reshape(10,3)

array([[ 5, 11,  3],
       [19,  9, 16],
       [ 4, 12,  1],
       [ 9, 11,  7],
       [ 4,  1,  4],
       [ 7,  0,  2],
       [19,  8, 19],
       [ 7,  2, 13],
       [13, 17,  6],
       [ 0, 11,  9]])

In [36]:
print(x)

[[ 5 11  3 19  9 16  4 12  1  9 11  7  4  1  4]
 [ 7  0  2 19  8 19  7  2 13 13 17  6  0 11  9]]


In [37]:
x1 =np.array([[2,3],[4,3]])
print(x1)

[[2 3]
 [4 3]]


In [38]:
x2= np.array([[4,5],[6,7]])
print(x2)

[[4 5]
 [6 7]]


In [39]:
np.vstack([x1,x2])

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [40]:
np.hstack([x1,x2])

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [41]:
np.concatenate([x1,x2],axis=0)  #vstack

array([[2, 3],
       [4, 3],
       [4, 5],
       [6, 7]])

In [42]:
np.concatenate([x1,x2],axis=1)   #hstack

array([[2, 3, 4, 5],
       [4, 3, 6, 7]])

In [43]:
x=np.random.randint(0,10,(4,6))
x

array([[4, 8, 4, 0, 8, 2],
       [9, 3, 4, 7, 6, 0],
       [1, 0, 4, 1, 5, 1],
       [6, 8, 9, 8, 3, 2]])

In [44]:
np.split(x,2,axis=0)

[array([[4, 8, 4, 0, 8, 2],
        [9, 3, 4, 7, 6, 0]]),
 array([[1, 0, 4, 1, 5, 1],
        [6, 8, 9, 8, 3, 2]])]

In [45]:
array1=np.array([[1,2,3],       #1+7,2+8,3+9   
                 [4,5,6]])      #4+10,5+11,6+12
array2=np.array([[7,8,9],
                 [10,11,12]])

sum_array=array1+array2
print("addition:\n*",sum_array)

addition:
* [[ 8 10 12]
 [14 16 18]]


In [46]:
array1=np.array([[1,2,3],
                 [4,5,6]])
array2=np.array([[7,8,9],
                 [10,11,12]])
array3=np.array([[8,6,9],
                [10,9,13]])

sum_array=array1+array2+array3
print("addition:\n*",sum_array)

addition:
* [[16 16 21]
 [24 25 31]]


In [47]:
a=np.array([0,1,6])
b=np.array([0,6,1])
sub=a-b
print(sub)

[ 0 -5  5]


In [48]:
#numpy broadcosting

a=np.array([[1,2],[6,8],[6,5]])
b=np.array([5,4])
print(a+b)


[[ 6  6]
 [11 12]
 [11  9]]
