# NumPy (Numerical Python)
    is a powerful library for numerical computations in Python.
    It provides support for arrays, matrices, and
    many mathematical functions to operate on these data structures.

In [64]:
x =[2,4,6,8,10]
for i in x:
  print(i/2)

1.0
2.0
3.0
4.0
5.0


In [65]:
import numpy as np
x=np.array([2,4,6,8,10])

print(x)

[ 2  4  6  8 10]


In [66]:
x*2

array([ 4,  8, 12, 16, 20])

In [67]:
type(x)

numpy.ndarray

In [68]:
#Numpy has Rich set of NumPy Functions:

## Set1 = Random Functions:

In [69]:
import numpy as np
np.random.randint(0,10,6)   #randint will generate randopm integer numbers

array([5, 7, 5, 8, 4, 4])

In [70]:
array=np.random.randint(0,10,(3,4))
array

array([[6, 1, 2, 3],
       [8, 2, 7, 1],
       [7, 8, 6, 4]])

In [71]:
np.random.randint(0,10,(2,3))

array([[8, 4, 3],
       [8, 5, 6]])

In [72]:
np.random.randint(100,200,2)   #Random Data from 0 to 1

array([136, 160])

In [73]:
#Numpy slicing
array[1: ,0:2]

array([[8, 2],
       [7, 8]])

In [74]:
x = np.array(array)

In [75]:
data = np.random.randint(0,10,(5,4))
data

array([[8, 9, 9, 1],
       [2, 5, 5, 0],
       [5, 0, 5, 2],
       [3, 0, 4, 2],
       [2, 8, 1, 5]])

In [76]:
data[1: , :2]

#

array([[2, 5],
       [5, 0],
       [3, 0],
       [2, 8]])

In [77]:
data[2:4,1: ]

array([[0, 5, 2],
       [0, 4, 2]])

In [78]:
data [2:4,1: ]

array([[0, 5, 2],
       [0, 4, 2]])

In [79]:
#Numpy

#1 D array:

import numpy as np
a=np.array([1,23,24])
print(a)

[ 1 23 24]


In [80]:
import numpy as np

#1D array
a =np.array([2,3,4])
print(a)

[2 3 4]


In [81]:
#2D array

b=np.array([[2,4,6],[8,10,12],[5,6,7]]),([[1,7,3],[5,5,6],[5,8,7]])
print(b)

(array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 5,  6,  7]]), [[1, 7, 3], [5, 5, 6], [5, 8, 7]])


In [82]:
#2D array

c=np.array([[2,4,6],[8,10,12],[5,3,4]])
print(c)

[[ 2  4  6]
 [ 8 10 12]
 [ 5  3  4]]


In [83]:
#Initialize Numpy arrays

#initialize 'x X y' dimensions with '0' values
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
import numpy as np

#full array with -6 values
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
#1D Array

a=np.array([1,2,3])
print(a)

[1 2 3]


In [87]:

# 2d array
a =np.array([[2,4,6],[4,5,6],[6,5,7]])

print(a)
print(type(a))
a.ndim

[[2 4 6]
 [4 5 6]
 [6 5 7]]
<class 'numpy.ndarray'>


2

In [88]:
#3d  array 
x= np.array([[[1,2,3], [4,5,6],[5,6,7]], [[4,5,6],[8,8,7],[8,9,7]]])
print(x)

print(type(x))
x.ndim

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[4 5 6]
  [8 8 7]
  [8 9 7]]]
<class 'numpy.ndarray'>


3

In [89]:
#Initialize Array:

#Initilize an array of 'x' X 'y' dimensions with 0

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
#Initilize an array of 'x' X 'y' dimensions with 1

b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [91]:
#Initilize 'x' and 'y' with an interval of z

np.arange(0,101,10) #

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [92]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [93]:
#initialize 'z' numbers between 'x' and 'y'
#devide upper and lower limit to equal measures

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [94]:
np.linspace(9,90,10)

array([ 9., 18., 27., 36., 45., 54., 63., 72., 81., 90.])

In [95]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [96]:
np.eye(5)  # eye: refer to identical matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [97]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [99]:
import numpy as np

# Create the NumPy array
data = np.array([[5, 4, 0, 1],
                  [11, 4, 10, 7],
                  [7, 10, 5, 6],
                  [7, 12, 10, 4],
                  [3, 7, 3, 4]])

# Print the array
print(data)

[[ 5  4  0  1]
 [11  4 10  7]
 [ 7 10  5  6]
 [ 7 12 10  4]
 [ 3  7  3  4]]


In [100]:
dt =[1,3,4]
sum(dt)

8

In [101]:
data.max()

12

In [102]:
data.mean()

6.0

In [103]:
data.sum()

120

In [104]:
#Fill SAME numbers in an array of dimensions 'x' X 'y'

np.full((4,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [105]:
#ndarray.shape:

a=np.array([[2,4,6],[5,6,7],[8,10,12]])
print(a)
print(a.shape)

[[ 2  4  6]
 [ 5  6  7]
 [ 8 10 12]]
(3, 3)


In [106]:
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)   #2,3

(2, 3)


In [107]:
#We can use ndarray.shape function to resize the array:
a=np.array([[2,4,6,4],[5,6,7,8],[8,10,12,4]]) #3,4 =12
print("Original Array:\n", a)
a.shape=(6,2)   #12 = 1,2,3,4,6,12 (1,12), (2,6),(3,4),(4,3),(6,2)(12,1)
print("Changed Array:\n",a)

a.shape=(4,3)
print("Changed Array:\n",a)

Original Array:
 [[ 2  4  6  4]
 [ 5  6  7  8]
 [ 8 10 12  4]]
Changed Array:
 [[ 2  4]
 [ 6  4]
 [ 5  6]
 [ 7  8]
 [ 8 10]
 [12  4]]
Changed Array:
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  8]
 [10 12  4]]


In [108]:
b=np.array([[1,2,3],[4,5,6],[5,8,8],[5,6,4]])
b.shape=(6,1,2)  # 12= 1*12,2*6,3*4, 4*3,6*2,1*12
print(b)
#print(b.size)
print(b.ndim)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[5 8]]

 [[8 5]]

 [[6 4]]]
3


In [109]:
z=np.arange(24)
print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,6,2) (4,2,3)
z.shape=(2,3,4)  #4,3,2
#3 dimensional
print(z)
print(z.ndim)  #.ndim= no of dimenssions in that array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [110]:
z=np.arange(30)
#print(z)
#1D array[0,1,2,3,.....,23]  # 1*24
#print(z)     #24 =1,2,3,4,6,8,12,24(1,24)(2,12),(3,8)
# For reshaping into 3D Array (2,5,3),(3,5,2),(1,10,3)
z.shape=(1,10,3)  #2,2,2,3
#3 dimensional
print(z)
print(z.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [111]:
Y =np.arange(200)  #0,1,.......,199
#print(Y)
#print(Y.size)    #200 =100*2 =50*2*2=25*2*2*2=5*5*2*2*2


Y.shape=(4,2,5,5) #5*5*4*2
print(Y)
print(Y.ndim)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]
   [ 20  21  22  23  24]]

  [[ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]
   [ 40  41  42  43  44]
   [ 45  46  47  48  49]]]


 [[[ 50  51  52  53  54]
   [ 55  56  57  58  59]
   [ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]]

  [[ 75  76  77  78  79]
   [ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]]


 [[[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]
   [120 121 122 123 124]]

  [[125 126 127 128 129]
   [130 131 132 133 134]
   [135 136 137 138 139]
   [140 141 142 143 144]
   [145 146 147 148 149]]]


 [[[150 151 152 153 154]
   [155 156 157 158 159]
   [160 161 162 163 164]
   [165 166 167 168 169]
   [170 171 172 173 174]]

  [[175 176 177 178 179]
   [180 181 182 183 184]
   [185 186 187 188 189]
   [190 191 192 193 194]
   [1

In [112]:
import numpy as np
b=np.array([[4,5,6],[6,8,10]])
print(b.shape)
print(b.ndim)
#Convert above array into 2D and 3D array
b.shape=(3,2)

print(b)#6=1,2,3,6

(2, 3)
2
[[ 4  5]
 [ 6  6]
 [ 8 10]]


In [113]:
#Addition Using numpy Function

np.multiply(10,20)

200

In [114]:
np.sum([20,10,3])

33

In [115]:
#Add the arrays
#axis=0 will add numbers by Columns
#axis =1 will add numbers by rows
np.sum([[0,1],[0,5],[3,5]],axis = 0)
np.sum([[0,1],[0,5],[3,5]],axis = 1)

array([1, 5, 8])

In [116]:
#axis=1 will add numbers by rows

np.sum([[0,1],[0,5],[3,5]],axis = 1)

array([1, 5, 8])

In [117]:
data

array([[ 5,  4,  0,  1],
       [11,  4, 10,  7],
       [ 7, 10,  5,  6],
       [ 7, 12, 10,  4],
       [ 3,  7,  3,  4]])

In [118]:
data.sum(axis=1)

array([10, 32, 28, 33, 17])

In [119]:
data.sum(axis=0)

array([33, 37, 28, 22])

In [120]:
data.min(axis=0)

array([3, 4, 0, 1])

In [121]:
data.argmin(axis=0)

array([4, 0, 0, 0], dtype=int64)

In [122]:
data.max(axis=1)

array([ 5, 11, 10, 12,  7])

In [123]:
data.mean()

6.0