Metrix in Data/Basic Descriptive Statiestics

1.min
2.max
3.mean
4.Mode
5. Median
6. Standard Deviation
7. Count
8. Q1, Q2, Q3, Q4
```

In [156]:
a= np.array([3,4])
b=np.array([5,6])

print(np.sum((a,b), axis=0))
print(np.sum((a,b), axis=1))

[ 8 10]
[ 7 11]


In [157]:
#Array comparions

#Element wise Comparison.. fun called as equal
import numpy as np

a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

print(np.equal(a,b)) #False,False,True
print(np.equal(a,c))

[False False  True]
[ True  True  True]


In [158]:
#Array wise comparison
import numpy as np

a=[1,2,4]
b=[2,4,4]
c=[1,2,4]

print(np.array_equal(a,b))  #
print(np.array_equal(a,c))  #

False
True


In [159]:
import numpy as np
d = np.array(24)
print(d)

24


In [160]:
d=np.arange(24)  #24 =12*2 , 6*4, 8*3
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [161]:
d.shape=(12,2)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [162]:
# Find the number Elements in array

import numpy as np

a=np.array([[1,2,3],[4,5,6],[5,8,12]])
print(a.size )   #
print(a.shape)   #
print(a.ndim)
print(a.dtype)
#

9
(3, 3)
2
int32


In [163]:
a=np.array([
    [[1,2,3,4],[4,5,6,8]],
     [[7,8,9,4],[4,5,5,6]]
])
print(a.size)
print(a.dtype)

import numpy as np



print(a.shape)  # Output: (2, 2, 4)
print(a.ndim)   # Output: 3

16
int32
(2, 2, 4)
3


# Finding the data type of an array

In [164]:
print(a.dtype)

int32


In [165]:
d=np.arange(24)  #[0,-----,23]
print(d)
print(d.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
int32


In [166]:
d=np.arange(24,dtype='float') #0,1,.....,23
print(d)
print(d.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
float64


I# Numpy array Mathematics- Sum

In [167]:
import numpy as np
np.sum([10,30,60,54,68,258])

a=[10,20]   #25+30
b=[20,5]

np.sum([a,b])

55

In [168]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],       #[8,10,12],[14,16,18]
                   [10, 11, 12]])

array3 = np.array([[8, 6, 9],      #[16,16,21],[24,25,31]
                   [10, 9, 13]])

# Adding the two arrays
sum_array = array1+array2+array3
print("Addition:\n", sum_array)
sum_array.ndim

Addition:
 [[16 16 21]
 [24 25 31]]


2

# Subtraction:

In [176]:
import numpy as np

np.subtract(10,20)

 #Subtraction of 3 arrays:

a=np.array([0,1,6])
b=np.array([0,5,3])
c=np.array([0,1,2])
Sub = a-b-c
print(Sub)

[ 0 -5  1]


In [177]:
a=[0,1]
b=[0,5]

np.subtract(a,b)

array([ 0, -4])

In [178]:
import numpy as np

a = np.array([[2, 4],
              [5,8]])
b = np.array([[4, 6],
              [3,5]])

# Perform element-wise subtraction
result = np.subtract(a, b)
print("Result of a - b:", result)  #

Result of a - b: [[-2 -2]
 [ 2  3]]


In [179]:
#Using Different Shapes(Broadcasting)
import numpy as np

a = np.array([[1, 2],[6, 8],[6,5]])
b = np.array([5,4])

# Addition from each row of a using broadcasting
result = a + b
print("Result of a + b with broadcasting:\n", result)

Result of a + b with broadcasting:
 [[ 6  6]
 [11 12]
 [11  9]]


In [180]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Subtracting the second array from the first array
difference_array = array1 - array2
print("Subtraction:\n", difference_array)

Subtraction:
 [[ 9 18 27]
 [36 45 54]]


# Multiplication of Numpy Array:

In [181]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


In [182]:
array1 = np.array([[1, 2],
                   [4, 5],
                   [4,6]])

array2 = np.array([[7, 8],
                  [4,1],
                   [5,2]
                   ])

# Multiplying the two arrays element-wise
product_array = array1 * array2
print("Multiplication:\n", product_array)

Multiplication:
 [[ 7 16]
 [16  5]
 [20 12]]


Matrix Multiplication:

the number of columns in the first matrix must be equal to the number of rows in the second matrix. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix. The product of matrices A and B is denoted as AB.

m*n, n*k      =

In [183]:
x1=np.random.randint(0,10,(2,2))
x2=np.random.randint(0,10,(2,2))

In [184]:
x1

array([[7, 2],
       [5, 9]])

In [185]:
x2

array([[7, 0],
       [2, 7]])

In [186]:
np.dot(x1,x2)

array([[53, 14],
       [53, 63]])

In [187]:
x1=np.random.randint(0,10,(2,3))
x2=np.random.randint(0,10,(3,2))

In [188]:
x1

array([[5, 3, 7],
       [4, 8, 7]])

In [189]:
x2

array([[8, 6],
       [8, 4],
       [4, 7]])

In [190]:
np.dot(x1,x2)

array([[ 92,  91],
       [124, 105]])

String Functions

In [191]:
x=np.array([1,2,3,'data'])

In [192]:
x

array(['1', '2', '3', 'data'], dtype='<U11')

In [193]:
np.char.capitalize(x)

array(['1', '2', '3', 'Data'], dtype='<U11')

In [194]:
np.char.center(x,10,fillchar='-')

array(['----1-----', '----2-----', '----3-----', '---data---'],
      dtype='<U10')

In [195]:
x=np.array([1,2,3,'data eNginEerIng'])

In [196]:
x

array(['1', '2', '3', 'data eNginEerIng'], dtype='<U16')

In [197]:
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))

['1' '2' '3' 'DATA ENGINEERING']
['1' '2' '3' 'data engineering']
['1' '2' '3' 'Data Engineering']


In [198]:
np.char.split(x)

array([list(['1']), list(['2']), list(['3']),
       list(['data', 'eNginEerIng'])], dtype=object)

In [199]:
y=np.array(["Data Science","Machine Learning"])

In [200]:
np.char.split(y,sep='e')

array([list(['Data Sci', 'nc', '']), list(['Machin', ' L', 'arning'])],
      dtype=object)

In [201]:
np.char.count(y,"i")

array([1, 2])

In [202]:
y

array(['Data Science', 'Machine Learning'], dtype='<U16')

In [203]:
np.char.startswith(y, "M")

array([False,  True])

In [204]:
np.char.replace(y,'a','xxxxxxx')

array(['Dxxxxxxxtxxxxxxx Science', 'Mxxxxxxxchine Lexxxxxxxrning'],
      dtype='<U28')

In [205]:
np.char.rjust(y,20,fillchar="*")

array(['********Data Science', '****Machine Learning'], dtype='<U20')

In [206]:
np.char.ljust(y,20,fillchar="*")

array(['Data Science********', 'Machine Learning****'], dtype='<U20')

#Time Base Functions:
- YYYY:MM:DD  HH:MM:SS  Time Stamp
- YYYY:MM:DD   Date
- HH:MM:SS      Time

#Purpose:
- extract month and identify
- can be found answers questions based on time series
- extracting yeras, week, days, studied




# Division of Arrays:

In [209]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[10, 20, 30],
                   [40, 50, 60]])

array2 = np.array([[3, 4, 5],
                   [10, 5, 3]])

# Dividing the first array by the second array element-wise
division_array = array1 / array2
print("Division:\n", division_array)
print(division_array.dtype)

Division:
 [[ 3.33333333  5.          6.        ]
 [ 4.         10.         20.        ]]
float64


# Calculating the Exponential:

This line calculates the exponential of each element in the array a.
The function np.exp() applies the exponential function
𝑒^a
  to each element in the array.
  

In [210]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 2, 3, 4, 5])

# Calculating the exponential of each element in the array
exp_a = np.exp(a)

print("Original array:", a)
print("Exponential of the array:", exp_a)  #e = 2.718281828459045

Original array: [1 2 3 4 5]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [211]:
import math
math.e

2.718281828459045

In [212]:
#Exponential of a 2D Array

import numpy as np

# Creating a 2D NumPy array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Calculating the exponential of each element in the 2D array
exp_b = np.exp(b)

print("Original 2D array:\n", b)
print("Exponential of the 2D array:\n", exp_b) #e^1,

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Exponential of the 2D array:
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


# Square Root (np.sqrt())
The np.sqrt() function computes the non-negative square root of each element in the input array.

In [213]:
import numpy as np

# Creating a NumPy array
a = np.array([1, 4, 9, 16, 25,37])

# Calculating the square root of each element
sqrt_a = np.sqrt(a)

print("Original array:", a)  #[1,4,9,16,25]
print("Square root of the array:", sqrt_a)  #[1.,2.,3.,4.,5.]

Original array: [ 1  4  9 16 25 37]
Square root of the array: [1.         2.         3.         4.         5.         6.08276253]


In [214]:
#expo, sqrt,sin,cos,log

a=np.array([2,4,6])

print("sqrt of a:", np.sqrt(a))
print("exp of a:", np.exp(a))
print("sin of a:", np.sin(a))
print("cos of a:", np.cos(a))
print("log of a:", np.log(a))

sqrt of a: [1.41421356 2.         2.44948974]
exp of a: [  7.3890561   54.59815003 403.42879349]
sin of a: [ 0.90929743 -0.7568025  -0.2794155 ]
cos of a: [-0.41614684 -0.65364362  0.96017029]
log of a: [0.69314718 1.38629436 1.79175947]


In [215]:
#Aggregate Functions:

#aggregate functions perform computations on arrays to return a single value.
#Here are some common aggregate functions in NumPy

a=np.array([1,2,4,5,6,7,8,9])
print("Sum:",np.sum(a))   # 42
print("Minimum Value:", np.min(a))   #1
print("Mean Value:", np.mean(a))     #mean =average
print("Median Value:", np.median(a)) #
print("Corelation Coefficient:", np.corrcoef(a))   #
print("Standard Deviation:", np.std(a))      #

Sum: 42
Minimum Value: 1
Mean Value: 5.25
Median Value: 5.5
Corelation Coefficient: 1.0
Standard Deviation: 2.6339134382131846


In [216]:
import numpy as np
x= np.random.randint(0,10,(4,6))
print(x)

[[2 3 2 9 8 7]
 [6 2 2 4 5 6]
 [8 6 9 6 1 3]
 [9 7 0 9 3 8]]


In [217]:
np.split(x,2,axis=0)  #It will split list into 2 parts

[array([[2, 3, 2, 9, 8, 7],
        [6, 2, 2, 4, 5, 6]]),
 array([[8, 6, 9, 6, 1, 3],
        [9, 7, 0, 9, 3, 8]])]

In [218]:
np.split(x,2,axis=1) #split into vertical parts

[array([[2, 3, 2],
        [6, 2, 2],
        [8, 6, 9],
        [9, 7, 0]]),
 array([[9, 8, 7],
        [4, 5, 6],
        [6, 1, 3],
        [9, 3, 8]])]

In [219]:
np.split(x,4,axis=0)

[array([[2, 3, 2, 9, 8, 7]]),
 array([[6, 2, 2, 4, 5, 6]]),
 array([[8, 6, 9, 6, 1, 3]]),
 array([[9, 7, 0, 9, 3, 8]])]

In [220]:
np.vsplit(x,2)

[array([[2, 3, 2, 9, 8, 7],
        [6, 2, 2, 4, 5, 6]]),
 array([[8, 6, 9, 6, 1, 3],
        [9, 7, 0, 9, 3, 8]])]

In [221]:
np.hsplit(x,2)

[array([[2, 3, 2],
        [6, 2, 2],
        [8, 6, 9],
        [9, 7, 0]]),
 array([[9, 8, 7],
        [4, 5, 6],
        [6, 1, 3],
        [9, 3, 8]])]

In [222]:
x.T  #Transpose- It will swap rows to column and column to rows

array([[2, 6, 8, 9],
       [3, 2, 6, 7],
       [2, 2, 9, 0],
       [9, 4, 6, 9],
       [8, 5, 1, 3],
       [7, 6, 3, 8]])

In [223]:
x=np.random.randint(0,10,(2,2))
print(x)

[[7 5]
 [7 0]]


In [224]:
np.median(x)

6.0