# Numpy Broadcasting

In [4]:
import numpy as np

a = np.array([1, 2.5, 3])
b = 2
c = a + b
print(c)

[3.  4.5 5. ]


In [5]:
# Broadcasting with Different Shapes

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 0, 1])
c = a + b
print(c)

[[2 2 4]
 [5 5 7]]


In [6]:
#Higher Dimensions

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6],[2,4,5]])
b = np.array([1])
#d=np.array([[2,3,4],[4,8,9]])
c = a + b
print(c)

[[2 3 4]
 [5 6 7]
 [3 5 6]]
