In [3]:
import numpy as np

In [15]:

array1=np.array([[1,2,3],
                 [4,5,6]])
array2=np.array([[7,8,9],
                 [10,11,12],
                 ])


sum_array=array1*array2
print("multiflication:\n*",sum_array)

multiflication:
* [[ 7 16 27]
 [40 55 72]]


In [27]:
#matrix multiflication

#m8n,n*k

x1=np.random.randint(0,5,(2,2))

x2=np.random.randint(0,5,(2,2))



In [28]:
x1

array([[4, 1],
       [4, 1]])

In [29]:
x2

array([[4, 2],
       [1, 3]])

In [ ]:
np.dot(x1,x2)